#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FILE_PATH_MAX 256

void escape_line(char *filtered_line, char *line, int line_len) {
  int filtered_index = 0;

  for (int i = 0; i < line_len; i++) {
    char c = line[i];

    switch (c) {
    case '\n': {
      filtered_line[filtered_index++] = '\\';
      filtered_line[filtered_index++] = 'n';
    } break;
    case '\r': {
      filtered_line[filtered_index++] = '\\';
      filtered_line[filtered_index++] = 'r';
    } break;

    case '\t': {
      filtered_line[filtered_index++] = '\\';
      filtered_line[filtered_index++] = 't';
    } break;

    case '\\': {
      filtered_line[filtered_index++] = '\\';
      filtered_line[filtered_index++] = '\\';
    } break;

    case '"': {
      filtered_line[filtered_index++] = '\\';
      filtered_line[filtered_index++] = '"';
    } break;

    default:
      filtered_line[filtered_index++] = c;
    }
  }

  filtered_line[filtered_index] = '\0';
}

int main(int argc, char *argv[]) {
  if (argc != 2) {
    printf("Usage: %s <file_path>\n", argv[0]);
    exit(1);
  }

  char *file_path = argv[1];
  int file_path_len = strlen(file_path);

  // get the macro name out of the file path.
  char define_name[file_path_len + 1];
  int i;
  for (i = 0; i < file_path_len; i++) {
    char c = file_path[i];
    if (c == '/') {
      define_name[i] = '_';
    } else if (c == '.') {
      break;
    } else {
      define_name[i] = toupper(c);
    }
  }
  define_name[i] = '\0';

  char variable_name[file_path_len + 1];
  for (i = 0; i < file_path_len; i++) {
    char c = file_path[i];
    if (c == '/') {
      variable_name[i] = '_';
    } else if (c == '.') {
      break;
    } else {
      // no uppercase conversion here.
      variable_name[i] = c;
    }
  }
  variable_name[i] = '\0';

  char target_path[FILE_PATH_MAX];
  sprintf(target_path, "%s.h", file_path);

  FILE *file = fopen(file_path, "r");

  // then, iterate over all the lines of the file.
  char line[256];
  char filtered_line[256 *
                     2]; // to remove all the escaped characters and whatnot

  FILE *target_file = fopen(target_path, "w");

  fprintf(target_file, "#pragma once\n");
  fprintf(target_file,
          "// This file was generated by mk_html.c, do not edit.\n");

  // make the macro version.
  fprintf(target_file, "#define %s \\\n", define_name);
  while (fgets(line, sizeof(line), file)) {
    // trim the last newline off of the line.
    int line_len = strlen(line);
    escape_line(filtered_line, line, line_len);
    // we don't need to add the newline, the filtration does that for us.
    fprintf(target_file, "\"%s\" \\\n", filtered_line);
  }

  fseek(file, 0, SEEK_SET);

  fprintf(target_file, "\nconst char* %s = \\\n", variable_name);
  int total_sz = 0;
  while (fgets(line, sizeof(line), file)) {
    // trim the last newline off of the line.
    int line_len = strlen(line);
    total_sz += line_len;

    escape_line(filtered_line, line, line_len);

    // we don't need to add the newline, the filtration does that for us.
    fprintf(target_file, "\"%s\"", filtered_line);
  }
  fprintf(target_file, ";\n");

  fprintf(target_file, "\nconst int %s_len = %d;\n", variable_name,
          total_sz + 1);

  fclose(file);
  fclose(target_file);

  return 0;
}
