#pragma once
// This file was generated by mk_html.c, do not edit.
#define HTML_ERROR \
"<!DOCTYPE>\n" \
"<html>\n" \
"<body>\n" \
"\t<h1>ERROR!</h1>\n" \
"\t<p>internal server error.</p>\n" \
"</body>\t\n" \
"</html>\n" \
"\n" \

const char* html_error = \
"<!DOCTYPE>\n""<html>\n""<body>\n""\t<h1>ERROR!</h1>\n""\t<p>internal server error.</p>\n""</body>\t\n""</html>\n""\n";

const int html_error_len = 92;
