#pragma once
// This file was generated by mk_html.c, do not edit.
#define HTML_INDEX \
"<!DOCTYPE html>\n" \
"<html lang=\"en\">\n" \
"<body>\n" \
"<div>\n" \
"\t<p>\n" \
"\t\thello world, how are things?\n" \
"\t</p>\n" \
"</div>\n" \
"</body>\n" \
"</html>\n" \

const char* html_index = \
"<!DOCTYPE html>\n""<html lang=\"en\">\n""<body>\n""<div>\n""\t<p>\n""\t\thello world, how are things?\n""\t</p>\n""</div>\n""</body>\n""</html>\n";

const int html_index_len = 112;
